name: Benchmark
on: [push, pull_request]
jobs:
  test:
    name: Bench
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.22
      uses: actions/setup-go@v5
      with:
        go-version: 1.22
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        fetch-depth: 1024

    # Commenting out this step for now while we test the PR comment portion
    # # TODO: Pin release
    # # TODO: Remove git-base
    # # TODO: Provide output
    # - name: Run Benchmark
    #   run: go run github.com/grafana/pyrobench@65a9bc2 -v compare --git-base 5eca05b1e4cf63df5d007ec6b13ce7394a0fffe3

    - uses: actions/github-script@v7
      id: create-comment
      if: ${{ github.event_name == 'pull_request' }}
      with:
        script: |
          return github.rest.issues.listComments({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
          });

    - name: Get result
      run: echo "${{steps.create-comment.outputs.result}}"
